USE [master]
GO

/****** Object:  Database [ThomasGreg]    Script Date: 22/03/2020 18:00:03 ******/
CREATE DATABASE [ThomasGreg]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ThomasGreg', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ThomasGreg.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ThomasGreg_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ThomasGreg_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ThomasGreg].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ThomasGreg] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ThomasGreg] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ThomasGreg] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ThomasGreg] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ThomasGreg] SET ARITHABORT OFF 
GO

ALTER DATABASE [ThomasGreg] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ThomasGreg] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ThomasGreg] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ThomasGreg] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ThomasGreg] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ThomasGreg] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ThomasGreg] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ThomasGreg] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ThomasGreg] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ThomasGreg] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ThomasGreg] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ThomasGreg] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ThomasGreg] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ThomasGreg] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ThomasGreg] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ThomasGreg] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ThomasGreg] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ThomasGreg] SET RECOVERY FULL 
GO

ALTER DATABASE [ThomasGreg] SET  MULTI_USER 
GO

ALTER DATABASE [ThomasGreg] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ThomasGreg] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ThomasGreg] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ThomasGreg] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ThomasGreg] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ThomasGreg] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ThomasGreg] SET  READ_WRITE 
GO

